server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dylandmr/java-spring-microservices
          #username: username
          #password: password
          search-paths:
            - "config-server/src/main/resources/config*"